pipeline {  
    agent any
    stages {
        stage("build") {
            echo "Building image"
        }
        
        stage("push") {
            echo "Pushing image to Harbor registery"
        }
    }
}