apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-backend-configmap

data:
  LISTEN_IP: "0.0.0.0"
  LISTEN_PORT: 8080
  KEYCLOAK_REALM: ICOSNET
  KEYCLOAK_BASE_URL: "http://auth-service.com"
  KEYCLOAK_CLIENT_ID: client