apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-backend
  labels:
    app: my-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: my-app-backend
    spec:
      containers:
        - name: my-app-backend
          image: container-reg.icosnet.local/sso/my-app-backend:1.3.0 # {"$imagepolicy": "flux-system:my-app-backend-policy"}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: my-app-backend-configmap
            - secretRef:
                name: my-app-backend-secret
